import Head from "next/head";
import Hero from '../assets/imgs/Hero.jpg'
import Image from "next/image";
import Link from "next/link";
import CatImg from '../assets/imgs/category.png'
import { useRouter } from "next/router";
import ProductCard from "@/components/ProductCard";

export default function Home({ categories, products }) {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full overflow-hidden">
        <Image src={Hero} priority={true} alt="Home" className="w-full height-auto overflow-hidden" />
      </div>

      <section className="text-gray-600 body-font">
        <div className="container px-5 py-10 md:py-15 mx-auto">
          <div className="flex flex-wrap w-full mb-6 md:mb-20">
            <div className="lg:w-1/2 w-full mb-6 lg:mb-0">
              <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Top Categories</h1>
              <div className="h-1 w-20 bg-indigo-500 rounded"></div>
            </div>
            <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">Explore our most popular categories, curated to help you find what you love quickly and easily.</p>
          </div>
          <div className="flex flex-wrap justify-center md:-m-4 mb-6 md:mb-12">
            {categories?.map((item) => (
              <Link href={`/products/${item?.slug}`} className="xl:w-1/4 md:w-1/2 p-4" key={item?.slug}>
                <div className="bg-gray-100 p-6 rounded-lg">
                  <Image className="h-40 rounded w-full object-cover object-center mb-6" src={CatImg} alt="category" />
                  <h2 className="text-lg text-gray-900 font-medium title-font text-center">{item?.name}</h2>
                </div>
              </Link>
            ))}
          </div>
          <section className="text-gray-600 body-font">
            <div className="container px-5 py-14 mx-auto">
              <h1 className="sm:text-3xl text-2xl font-medium title-font mb-8 text-gray-900">Featured Products</h1>
              <div className="flex flex-wrap -m-4">
                {products?.products?.map((item) => (
                  <ProductCard data={item} key={item.id} />
                ))}
              </div>
            </div>
          </section>
          <div className="flex justify-center">
            <button onClick={() => router.push('/products')} className="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none cursor-pointer hover:bg-indigo-600 rounded">
              See All Products
            </button>
          </div>
        </div>
      </section>

    </>
  );
}

export async function getServerSideProps() {
  const catResponse = await fetch('https://dummyjson.com/products/categories')
  const prodResponse = await fetch('https://dummyjson.com/products?limit=8')
  const categories = await catResponse.json()
  const products = await prodResponse.json()
  return {
    props: {
      categories: categories,
      products: products
    }
  };
}
